### ISSUE TITLE
新首页很赞以及个人一些意见

### ISSUE THREAD

**Issue by lizheming** [ljsabc/Mirrors-Newindex#1]
不是科大的学生就不在Google Groups上吐槽了，新首页很赞，比之前那个要好看很多。整体风格没有问题。但是总觉得Title这个“Another infinity”不好看，不是样式的问题，就是感觉这两个词做标题很不好看...

另外，获取ISO镜像的小窗的关闭按钮的交互没做好，cursor设置个pointer或者给hover加个背景神马的都算是比较正常的吧。

另外，为啥要吐槽AJAX，原生写起来也不麻烦额，好吧，我就是来为AJAX表不平的，大概。

推荐直接将JSON数据写到HTML页面中的形式，而不是目前这种逆天的徒手用JS加上去（说真的，当时看到都吓到了( ⊙ o ⊙ )！，希望这只是预览版的东西）。

最后的最后，再赞一下footer的3L，非常漂亮！

以上。

**Comment by ljsabc** [comment]
我只是个苦逼的前端工程师啊，哪儿来的文字功底，Another infinity也就是_无限的可能_啦，不知道会不会有更好的文字贡献出来
那个hover我改一下就是了，倒不是很麻烦
json写到HTML里其实也就是eval一下的问题，我当时在DotA脑子有点进水，在这点上万分感谢。

总之感谢反馈，这是我无上的荣耀（第一个issue？

**Comment by lizheming** [comment]
哈哈，赞苦逼的... 

嘛，可能是我个人的问题。对于英文做标题这种行为，我注重的不是样式，不是英文的优美，而是特别喜欢注重英文上中下给人的一种均匀感，比如iPhone这个词我就比较喜欢，P虽然作为大写占用上部分的空间，但是一点都没有感觉喧宾夺主把下部分的光辉给夺取了，上下显得特别的匀称。我大概想要说的是这个意思吧。

Another inifinity 这个词本身是很好的，但是inifinity这个词所有的字母都是下部分的，可能是这个我觉得不大习惯吧。对于这个，比较赞一下前面的Another，因为another本身也是一个情况，把首字大写之后上部分的感觉就有了（但是还是稍显不够）。我尝试着写成“Another Inifinity”换上衬线的字体之后感觉还不错，推荐你试试比较一下。

（嘛，我也只是一个业余的，上面的是我的个人感觉，仅供参考的说，具体你们随意哈。）

话说po主应该是女生吧，第一次见到玩DotA的女生。。（相比较来说，我就比较喜欢打成DOTA，因为DotA上半部分和两边的感觉太重，中间非常不厚实，哈哈！）

我也是随意吐槽，勿需感谢，荣耀什么的你就随意吧，哈哈！确实是第一个issue，不过嘛...好像你的github上也没啥东西（没东西你让人怎么吐槽啊←_←喂喂！）
